name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ join(matrix.config.*, '-') }}
    runs-on: ${{ matrix.config.os }}
    env:
      CXX: ccache ${{ matrix.config.compiler }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
