name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ join(matrix.config.*, '-') }}
    runs-on: ${{ matrix.config.os }}
    env:
      CXX: ${{ matrix.config.compiler }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: get netns script
      run: wget https://raw.githubusercontent.com/kametan0730/interface_2022_11/master/netns-scripts/chapter5-netns.sh -O netnsh.sh
    - name: create netns
      run: ./netnsh.sh
