name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ join(matrix.config.*, '-') }}
    runs-on: ${{ matrix.config.os }}
    env:
      CXX: ${{ matrix.config.compiler }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: create netns
      run: wget -O - https://raw.githubusercontent.com/kametan0730/interface_2022_11/master/netns-scripts/chapter5-netns.sh | sudo bash
    - name: check netns
      run: sudo ip netns exec router1 ip a
    - name: run
      run: sudo ip netns exec router1 make run &
    - name: ping
      run: sudo ip netns exec host0 ping -c 4 192.168.1.1
      
